server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: recursos-service
          uri: https://modulorecursoinnovatech.onrender.com/
          predicates:
            - Path=/api/v1/usuarios/** 
          filters:
            - AuthenticationFilter

# Monitoreo para Docker
management:
  endpoints:
    web:
      exposure:
        include: health, info
